### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by duboz** [vle-forge/irritator#85]
After unchecking the box "lock windows" in the "view" menu, irritator crashes if we try to resize main or components list window.

(gdb) bt
#0  0x00007ffff7a46a7c in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff79f2476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff79d87f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff79d871b in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff79e9e96 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00005555556ebe0c in ImGui::ErrorCheckEndFrameSanityChecks() ()
#6  0x00005555556dfb11 in ImGui::EndFrame() ()
#7  0x00005555556dff72 in ImGui::Render() ()
#8  0x000055555579217d in main ()

(gdb) cont
Program terminated with signal SIGABRT, Aborted.

**Comment by duboz** [comment]
This bug seems no longer existing since last pushes.
